"""ANSI-escape renderer + standalone terminal player script writer.

Closest export to the towel.blinkenlights.nl / telnet-asciimation aesthetic:
a self-contained player.py that clears the screen, prints a frame, sleeps,
and loops -- runnable directly in a real terminal.
"""
from __future__ import annotations

import json
from pathlib import Path
from threading import Event
from typing import Callable

from ascii_video.core.grid import FrameGrid

from .base import FrameStream

CLEAR = "\x1b[H\x1b[2J"
RESET = "\x1b[0m"

_UNSET = object()


def grid_to_ansi(grid: FrameGrid) -> str:
    """Row-run-length-grouped: emit a color escape only when the color
    actually changes, not once per character."""
    lines = []
    for y in range(grid.rows):
        parts: list[str] = []
        current_color = _UNSET
        for x in range(grid.cols):
            ch = str(grid.chars[y, x])
            # Space is invisible regardless of color, so treat it as "no
            # color" -- this both shrinks the output a lot (no per-cell color
            # churn across blank runs/backgrounds) and avoids ever painting a
            # visible background tint behind what should be empty canvas.
            color = tuple(int(v) for v in grid.colors[y, x]) if grid.colors is not None and ch != " " else None
            if color != current_color:
                if color is not None:
                    parts.append(f"\x1b[38;2;{color[0]};{color[1]};{color[2]}m")
                else:
                    parts.append(RESET)
                current_color = color
            parts.append(ch)
        lines.append("".join(parts) + RESET)
    return "\n".join(lines)


def export(
    frames: FrameStream,
    out_path: Path,
    options: dict,
    progress_cb: Callable[[int, int], None] | None = None,
    cancel_event: Event | None = None,
) -> None:
    out_path = Path(out_path)
    total = options.get("total_frames", 0)
    frame_data: list[list] = []
    for i, (delay_ms, grid) in enumerate(frames):
        if cancel_event is not None and cancel_event.is_set():
            break
        frame_data.append([delay_ms, grid_to_ansi(grid)])
        if progress_cb is not None:
            progress_cb(i + 1, total)

    write_player_script(frame_data, out_path)


def write_player_script(frame_data: list[list], out_path: Path) -> None:
    out_path = Path(out_path)
    data_path = out_path.with_suffix(".frames.json")
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(frame_data, f)

    script = f'''#!/usr/bin/env python3
"""Standalone ANSI terminal player, generated by ASCII Video.

Usage: python {out_path.name} [--once]
"""
import json
import sys
import time
from pathlib import Path

DATA_FILE = Path(__file__).with_name({data_path.name!r})


def main() -> None:
    frames = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    loop = "--once" not in sys.argv
    try:
        while True:
            for delay_ms, text in frames:
                sys.stdout.write("\\x1b[H\\x1b[2J")
                sys.stdout.write(text)
                sys.stdout.flush()
                time.sleep(max(0, delay_ms) / 1000.0)
            if not loop:
                break
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
'''
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(script)
    try:
        out_path.chmod(0o755)
    except OSError:
        pass
